appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: fv1jD2Y+H4Yp3tWbUVom/5tLPiEw9IJ6y6cm25yAo77TOboRcGk0N5dJZIYgMhjeVPy2+sSXvQGAWfoPBbHqpnJSGPdztEoUKO82PwfB5zCWzaFv4PYIIUsw7fMPcN/AaxXZQk9nY76wFTEYpPPw1b0k1S0GFPTIXMLtMpRde1U4Q8pWqleNvi/rANg7KGM+BFpCTPaLohigRQ5kkBR7ZqtFIVsLyCx+jbfcM2lstWn6fuGdeGjj6lo5ow3pn2K6U5cHNLBUNU2oTNX4GEN3KG+PbWjJHWp8iv7kuwoxRIIA1ghQYPo+oXhllRJ4f+UEHZa75a/Y1+DSvuewzdFFY8491Ipoqxtg9LoPDUkGPiLJYlyrbuPSQNqNVMyscqaDw03jhWildx0O9sN8g41xkOdcpFu5eoddMawhE0gkkmg5RDpwgjGqUaY09uFkj45/oML6XRzVRsSuiqIDshW3HRJQSCzTGB+Oi1+vPKoGsQJjbG5RepL7m0QjcWP5DHrL6lm5zVlku6aHIL7eGq/asisbQl8gHxd1EbIrxsx1AqxZL1qDE4/Pzl3OT8noY33DKvrOrkSM5iR0T+lDratfNh6Q+x+23EPYFaNxve9Cvol4IdECJ1sCQSOVoiWCIjpMl7u35cwvRwW0F/D77FzHmYFx1clZJmtiMsfqovdpbuI=}
provider:
  linux_ppc64le: default
  linux_aarch64: default
